language: scala

scala:
  - 2.11.8

before_script:
  - docker run --name forecast-api -p=9072:8080 vidible/forecast-api:2.0.0

script:
  # Build client and test
  - cd client && sbt compile test
  # Build server
  - cd ../server && mvn clean install docker:build

after_success:
  - cd ../ && ./script/deploy.sh
