language: scala

scala:
  - 2.11.8

before_script:
  - docker login -u=$DOCKERHUB_UNAME -p=$DOCKERHUB_PASS

script:
  # Build client jar and push to Maven Central
  - cd client && echo "build client" #&& sbt compile publishSigned sonatypeRelease
  # Build server and push image to Dockerhub
  - cd ../server && echo "build server" #&& mvn clean install docker:build && docker push vidible/forecast-api:2.0.0

after_success:
  - cd ../ && ./script/deploy.sh #cd client && echo "deploy client" && cd ../server && echo "deploy server"
