language: scala

scala:
  - 2.11.8

cache:
  directories:
  - $HOME/.m2
  - $HOME/.ivy2

services:
  - docker

script:
  # Build server
  - cd server && mvn clean install docker:build
  # Build client and run tests against server
  - docker run --name forecast-api -p=9072:8080 vidible/forecast-api:2.0.1 &
  - cd ../client && sbt compile test
  - docker kill forecast-api

after_success:
  - cd ../ && ./script/deploy.sh
