language: scala

scala:
  - 2.11.8

script:
  # Build client and test
  - cd client && sbt compile test
  # Build server
  - cd ../server && mvn clean install docker:build

after_success:
  - cd ../ && ./script/deploy.sh
