language: scala

scala:
  - 2.11.8

before_script:
  - docker login -u=$DOCKERHUB_UNAME -p=$DOCKERHUB_PASS

script:
  - cd client && sbt compile #publishSigned sonatypeRelease
  - wget https://archive.apache.org/dist/maven/maven-3/3.3.9/binaries/apache-maven-3.3.9-bin.zip && unzip -qq apache-maven-3.3.9-bin.zip
export M2_HOME=$PWD/apache-maven-3.3.9 && export PATH=$M2_HOME/bin:$PATH
  - cd ../server && mvn clean install docker:build && docker push vidible/forecast-api:2.0.0
