matrix:
  include:
    - language: scala
      scala: 2.11.8
      before_script:
        - cd client
      script:
        - sbt publishSigned sonatypeRelease

  include:
    - language: java
      before_script:
        - cd server
        - docker login -u=$DOCKERHUB_UNAME -p=$DOCKERHUB_PASS
      script:
        - mvn clean install docker:build
        - docker push vidible/forecast-api:2.0.0
